[placeholders.description]
type = "string"
prompt = "Enter a short description of the project"

[placeholders.git-username]
type = "string"
prompt = "Enter your Github username / organization"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.year]
type = "string"
prompt = "Enter the year (for copyright completion)"
regex = "^[0-9]+$"

[placeholders.license]
type = "string"
prompt = "Which license to use ?"
choices = ["MIT", "GNU v3", "Apache v2"]
default = "MIT"

[placeholders.license_headers]
type = "bool"
prompt = "Want license in the file headers ?"
default = true
